---
# tasks file for Ansible-PgSQL-DB-User
- name: Ensure Databases Exist
  community.postgresql.postgresql_db:
    login_host: "{{ postgresql_login_host }}"
    login_user: "{{ postgresql_login_username }}"
    login_password: "{{ postgresql_login_password }}"
    name: "{{ item.db_name }}"
    encoding: "{{ item.encoding }}"
    lc_collate: "{{ item.lc_collate }}"
    lc_ctype: "{{ item.lc_ctype }}"
    template: "template0"
  with_items: "{{ postgresql_db_users }}"

- name: Ensure Users Exist
  community.postgresql.postgresql_user:
    login_host: "{{ postgresql_login_host }}"
    login_user: "{{ postgresql_login_username }}"
    login_password: "{{ postgresql_login_password }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
  with_items: "{{ postgresql_db_users }}"

- name: Ensure Default Privileges for Users
  community.postgresql.postgresql_query:
    login_host: "{{ postgresql_login_host }}"
    login_user: "{{ postgresql_login_username }}"
    login_password: "{{ postgresql_login_password }}"
    db: "{{ item.db_name }}"
    query: "{{ lookup('template', 'queries.sql.j2') }}"
  with_items: "{{ postgresql_db_users }}"
